name: Build No Cache

on:
  workflow_dispatch:
  schedule:
    - cron: "30 12 * * 0"
    # Will run once a week on Sunday afternoon

jobs:
  build-no-cache:
    outputs:
      docker-image-tag: ${{ steps.build-image.outputs.tag }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Build docs with middleman
        run: make build

      - name: Build without cache and push docker image
        id: build-image
        uses: DFE-Digital/github-actions/build-docker-image@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          context: .
          reuse-cache: false
          snyk-token: ${{ secrets.SNYK_TOKEN }}

      - name: Notify teams channel failure
        if: ${{ failure() }}
        uses: DFE-Digital/github-actions/send-to-teams-channel@master
        with:
          teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          title: Build failure
          service: ${{ vars.TEAMS_MSG_SERVICE_NAME }}
          message: |
            Rebuild docker cache failure
