name: Delete Review App

on:
  pull_request:
    branches:
      - master
    types:
      - closed
  workflow_dispatch:
    inputs:
      pr_number:
        description: PR number of review app to delete
        required: false
        type: string

jobs:
  delete-review-app:
    name: Delete Review App ${{ github.event.pull_request.number || github.event.inputs.pr_number }}
    concurrency: deploy_review_${{ github.event.pull_request.number || github.event.inputs.pr_number }}
    runs-on: ubuntu-latest
    if: >
      (github.event.action == 'closed') ||
      (github.event_name == 'workflow_dispatch')

    environment: review
    permissions:
      pull-requests: write
      id-token: write

    steps:
      - uses: DFE-Digital/github-actions/delete-review-app@master
        with:
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          terraform-base: terraform/application
          pr-number: ${{ github.event.pull_request.number || github.event.inputs.pr_number }}
          resource-group-name: s189t01-techg-rv-rg
          storage-account-name: s189t01techgrvtfsa
          container-name: terraform-state
          tf-state-file: ${{ github.event.pull_request.number || github.event.inputs.pr_number }}_kubernetes.tfstate
